import {setAdminRoute} from './navigation.js?v=12';
import {rpc,accountError} from './accounts.js?v=6';
import {validateProblem,parseProblemImport,validateSource,getSources} from './problem-store.js?v=10';
export function setupAdmin(ctx) {
 const $=id=>document.getElementById(id);let rows=[],selected=null,admin=false,accountId=null,token=0,busy=false,pendingImport=[],grantTarget=null,fileToken=0; 
 function setBusy(value){busy=value;for(const el of $('admin-form').querySelectorAll('input,select,textarea,button'))el.disabled=value;$('admin-choose').disabled=value;$('admin-new').disabled=value;$('admin-reload').disabled=value;for(const id of ['admin-source-name','admin-source-add','admin-import-file','admin-grant-username','admin-grant-find','admin-grant-submit'])$(id).disabled=value;$('admin-import-submit').disabled=value||!pendingImport.length;}
 function refreshSources(chosen=$('admin-source').value){$('admin-source').replaceChildren();for(const name of getSources(rows,[...ctx.sources(),...(chosen?[chosen]:[])])){const option=document.createElement('option');option.value=name;option.textContent=name;$('admin-source').append(option);}$('admin-source').value=[...$('admin-source').options].some(o=>o.value===chosen)?chosen:'Codeforces';}
 function renderChoices(){const query=$('admin-search').value.trim().toLowerCase();$('admin-choose').replaceChildren();const option=(value,label)=>{const n=document.createElement('option');n.value=value;n.textContent=label;$('admin-choose').append(n);};option('','Шинэ бодлого нэмэх');
  for(const p of rows.filter(p=>(!p.archived||$('admin-show-archived').checked||p.number===selected?.number)&&([p.title,p.number,'#'+p.number,'#'+String(p.number).padStart(3,'0'),...p.tags].join(' ').toLowerCase().includes(query)||p.number===selected?.number)))option(String(p.number),'#'+p.number+' · '+p.title+(p.archived?' · Хассан':''));$('admin-choose').value=selected?String(selected.number):'';
 }
 function edit(p){selected=p;$('admin-form').reset();$('admin-title').value=p?.title||'';refreshSources(p?.source||'Codeforces');$('admin-ref').value=p?.ref||'';$('admin-url').value=p?.url||'';$('admin-rating').value=p?.rating||1400;$('admin-rating-kind').value=p?.ratingKind||'official';$('admin-level').value=p?.level||'Practice';$('admin-priority').checked=!!p?.priority;$('admin-tags').value=p?.tags?.join(', ')||'';$('admin-lesson').value=p?.lesson||'';$('admin-editorial').value=p?.editorialUrl||'';
  for(let i=0;i<3;i++){ $('admin-hint-mn-'+i).value=p?.hints?.[i]||'';$('admin-hint-en-'+i).value=p?.hintsEn?.[i]||'';}
  $('admin-problem-id').textContent=p?'Бодлогын ID: #'+p.number+' · '+(p.archived?'Хассан':'Идэвхтэй'):'Шинэ бодлогын ID хадгалах үед автоматаар олгогдоно.';
  $('admin-archive').hidden=!p;$('admin-archive').textContent=p?.archived?'Бодлогыг сэргээх':'Бодлогыг хасах';$('admin-save').textContent=p?'Өөрчлөлт хадгалах':'Бодлого нэмэх';renderChoices();
 }
 async function load(){if(!admin||busy)return;const request=++token,uid=ctx.user()?.id;$('admin-message').textContent='Бодлогуудыг ачаалж байна…';
  try{const list=await rpc(ctx.client(),'get_admin_catalog');if(request!==token||uid!==ctx.user()?.id)return;rows=list||[];selected=selected?rows.find(p=>p.number===selected.number)||null:null;edit(selected);$('admin-message').textContent=rows.length+' бодлого · Хассан бодлогыг сэргээж болно.';}
  catch(e){if(request===token)$('admin-message').textContent=accountError(e);}
 }
 async function checkRole(){const request=++token,uid=ctx.user()?.id;admin=false;rows=[];selected=null;setAdminRoute(false);if(!uid||!ctx.client())return;
  try{const allowed=await rpc(ctx.client(),'is_admin');if(request!==token||uid!==ctx.user()?.id)return;admin=allowed===true;setAdminRoute(admin);if(admin){edit(null);void load();void loadAdmins();}}
  catch{ /* No client-side email or metadata fallback can grant admin rights. */ }
 }
 function input(){return validateProblem({title:$('admin-title').value,source:$('admin-source').value,ref:$('admin-ref').value,url:$('admin-url').value.trim(),rating:$('admin-rating').value,ratingKind:$('admin-rating-kind').value,level:$('admin-level').value,priority:$('admin-priority').checked,tags:$('admin-tags').value.split(','),hints:Array.from({length:3},(_,i)=>$('admin-hint-mn-'+i).value.trim()).filter((v,_,all)=>all.some(Boolean)),hintsEn:Array.from({length:3},(_,i)=>$('admin-hint-en-'+i).value.trim()).filter((v,_,all)=>all.some(Boolean)),lesson:$('admin-lesson').value,editorialUrl:$('admin-editorial').value.trim()});}
 $('admin-form').onsubmit=async event=>{event.preventDefault();if(!admin||busy||!$('admin-form').reportValidity())return;const uid=ctx.user()?.id;let payload;try{payload=input();}catch(e){$('admin-message').textContent=e.message;return;}setBusy(true);$('admin-message').textContent='Хадгалж байна…';
  try{const saved=await rpc(ctx.client(),'admin_save_problem',{p_body:payload,p_number:selected?.number||null,p_revision:selected?.revision||null});if(uid!==ctx.user()?.id)return;selected=saved;await ctx.refreshCatalog();setBusy(false);await load();$('admin-message').textContent='#'+saved.number+' хадгалагдлаа.';}
  catch(e){if(uid===ctx.user()?.id)$('admin-message').textContent=accountError(e);}finally{setBusy(false);}
 };
 $('admin-archive').onclick=async()=>{if(!selected||!admin||busy)return;const p=selected,wasArchived=p.archived,uid=ctx.user()?.id;if(!wasArchived&&!window.confirm('#'+p.number+' · '+p.title+' бодлогыг жагсаалтаас хасах уу? Сэргээж болно; progress хадгалагдана.'))return;setBusy(true);
  try{await rpc(ctx.client(),'admin_archive_problem',{p_number:p.number,p_revision:p.revision,p_archived:!wasArchived});if(uid!==ctx.user()?.id)return;await ctx.refreshCatalog();setBusy(false);await load();$('admin-message').textContent=wasArchived?'Бодлого сэргээгдлээ.':'Бодлогыг жагсаалтаас хаслаа. Progress хадгалагдсан.';}
  catch(e){if(uid===ctx.user()?.id)$('admin-message').textContent=accountError(e);}finally{setBusy(false);}
 };
 $('admin-choose').onchange=()=>{edit(rows.find(p=>p.number===Number($('admin-choose').value))||null);$('admin-message').textContent='';};$('admin-new').onclick=()=>{edit(null);$('admin-message').textContent='';};$('admin-reload').onclick=()=>void load();$('admin-search').addEventListener('input',renderChoices);$('admin-show-archived').onchange=renderChoices;
 $('admin-source').onchange=()=>{if($('admin-source').value!=='Codeforces')$('admin-rating-kind').value='estimated';};

 $('admin-source-form').onsubmit=async event=>{event.preventDefault();if(!admin||busy||!$('admin-source-form').reportValidity())return;const uid=ctx.user()?.id;let name;try{name=validateSource($('admin-source-name').value);}catch(e){$('admin-source-message').textContent=e.message;return;}setBusy(true);$('admin-source-message').textContent='Хадгалж байна…';try{const saved=await rpc(ctx.client(),'admin_add_source',{p_name:name});if(uid!==ctx.user()?.id)return;await ctx.refreshCatalog();refreshSources(saved);$('admin-source').dispatchEvent(new Event('change'));$('admin-source-name').value='';$('admin-source-message').textContent=saved+' source хадгалагдлаа.';}catch(e){if(uid===ctx.user()?.id)$('admin-source-message').textContent=accountError(e);}finally{setBusy(false);}};

 async function loadAdmins(){const uid=ctx.user()?.id;try{const list=await rpc(ctx.client(),'admin_list');if(uid!==ctx.user()?.id||!admin)return;$('admin-list').replaceChildren();for(const p of list||[]){const li=document.createElement('li');li.textContent='@'+p.username+(p.full_name?' · '+p.full_name:'')+(p.is_primary?' · Үндсэн админ':'');$('admin-list').append(li);}}catch(e){if(uid===ctx.user()?.id)$('admin-grant-message').textContent=accountError(e);}}
 $('admin-import-file').onchange=async()=>{const request=++fileToken,uid=ctx.user()?.id;pendingImport=[];$('admin-import-submit').disabled=true;$('admin-import-preview').replaceChildren();$('admin-import-message').textContent='';const file=$('admin-import-file').files[0];if(!file||!admin)return;
  try{if(file.size>2097152)throw new Error('JSON файл 2 MB хүртэл байна.');let document;try{document=JSON.parse((await file.text()).replace(/^\uFEFF/,''));}catch{throw new Error('JSON файлын бичлэг буруу байна.');}if(request!==fileToken||uid!==ctx.user()?.id)return;const list=parseProblemImport(document);for(const p of list)if(rows.some(r=>r.url===p.url||(r.source.toLowerCase()===p.source.toLowerCase()&&r.ref.toLowerCase()===p.ref.toLowerCase())))throw new Error(p.title+': энэ бодлого санд байна (хассан бодлого ч багтана).');pendingImport=list;for(const p of list){const li=window.document.createElement('li');li.textContent=p.title+' · '+p.source+' '+p.ref+' · '+p.rating;$('admin-import-preview').append(li);}$('admin-import-message').textContent=list.length+' бодлого бэлэн. Нэмэх товчийг дарж хадгална.';$('admin-import-submit').disabled=busy;}
  catch(e){if(request===fileToken&&uid===ctx.user()?.id)$('admin-import-message').textContent=e.message;}
 };
 $('admin-import-submit').onclick=async()=>{if(!admin||busy||!pendingImport.length)return;const uid=ctx.user()?.id,payload=pendingImport;setBusy(true);$('admin-import-message').textContent='Нэмж байна…';
  try{const saved=await rpc(ctx.client(),'admin_import_problems',{p_problems:payload});if(uid!==ctx.user()?.id)return;pendingImport=[];$('admin-import-file').value='';$('admin-import-preview').replaceChildren();await ctx.refreshCatalog();setBusy(false);await load();$('admin-import-message').textContent=saved.length+' бодлого нэмэгдлээ. ID: '+saved.map(p=>'#'+p.number).join(', ');}
  catch(e){if(uid===ctx.user()?.id)$('admin-import-message').textContent=accountError(e);}finally{setBusy(false);}
 };
 $('admin-grant-username').oninput=()=>{grantTarget=null;$('admin-grant-submit').hidden=true;$('admin-grant-preview').textContent='';$('admin-grant-message').textContent='';};
 $('admin-grant-form').onsubmit=async event=>{event.preventDefault();if(!admin||busy)return;grantTarget=null;$('admin-grant-submit').hidden=true;const uid=ctx.user()?.id,name=$('admin-grant-username').value.trim().replace(/^@/,'').toLowerCase();setBusy(true);
  try{const id=await rpc(ctx.client(),'get_profile_id',{p_username:name});if(!id)throw new Error('Хэрэглэгч олдсонгүй.');const profiles=await rpc(ctx.client(),'get_public_profile',{p_user_id:id}),p=profiles?.[0];if(uid!==ctx.user()?.id)return;if(!p)throw new Error('Profile олдсонгүй.');grantTarget=id;$('admin-grant-preview').textContent='@'+p.username+' · '+(p.full_name||'Нэр оруулаагүй')+' · '+(p.school||'Сургууль оруулаагүй');$('admin-grant-message').textContent='Энэ хэрэглэгчийг админ болгох бол доорх товчийг дарна уу.';$('admin-grant-submit').hidden=false;}
  catch(e){if(uid===ctx.user()?.id)$('admin-grant-message').textContent=accountError(e);}finally{setBusy(false);}
 };
 $('admin-grant-submit').onclick=async()=>{if(!admin||busy||!grantTarget)return;const uid=ctx.user()?.id,target=grantTarget;setBusy(true);
  try{await rpc(ctx.client(),'admin_grant',{p_user_id:target});if(uid!==ctx.user()?.id)return;grantTarget=null;$('admin-grant-submit').hidden=true;$('admin-grant-message').textContent='Админ эрх олголоо. Тухайн хэрэглэгч дахин нэвтэрч Admin хэсгээ нээнэ.';await loadAdmins();}
  catch(e){if(uid===ctx.user()?.id)$('admin-grant-message').textContent=accountError(e);}finally{setBusy(false);}
 };
 return {sourcesChanged(){refreshSources();},accountChanged(){const id=ctx.user()?.id||null;if(id===accountId)return;accountId=id;token++;fileToken++;pendingImport=[];grantTarget=null;$('admin-import-file').value='';$('admin-import-preview').replaceChildren();$('admin-list').replaceChildren();$('admin-grant-form').reset();$('admin-grant-submit').hidden=true;for(const key of ['admin-import-message','admin-grant-message','admin-grant-preview','admin-source-message'])$(key).textContent='';setBusy(false);$('admin-form').reset();$('admin-source-form').reset();void checkRole();},connected(){void checkRole();}};
}
